import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import inquirer from "inquirer";

// Interactive setup wizard. Mirrors quickLaunch's `npm run config`, but writes a
// single .env (consumed by Vite for the frontend and by the server) instead of
// string-replacing source templates.

interface Answers {
  title: string;
  description: string;
  logo: string;
  favicon: string;
  mapsKey: string;
  apiBaseUrl: string;
  projectId: string;
  storage: "firestore" | "gcs" | "memory";
  collection?: string;
  bucket?: string;
  object?: string;
}

async function run() {
  const answers = await inquirer.prompt<Answers>([
    { type: "input", name: "title", message: "Dashboard name?", default: "Google Dash" },
    { type: "input", name: "description", message: "Describe your dashboard use-case:", default: "A situational-awareness dashboard" },
    { type: "input", name: "logo", message: "Logo image source:", default: "/logo.svg" },
    { type: "input", name: "favicon", message: "Favicon location:", default: "/favicon.ico" },
    { type: "input", name: "mapsKey", message: "Google Maps API key:" },
    { type: "input", name: "apiBaseUrl", message: "API base URL:", default: "http://localhost:3000" },
    { type: "input", name: "projectId", message: "GCP project id:" },
    {
      type: "list",
      name: "storage",
      message: "Where should annotations be stored?",
      choices: [
        { name: "Firestore (document store, per-feature)", value: "firestore" },
        { name: "Cloud Storage (single GeoJSON object)", value: "gcs" },
        { name: "In-memory (local dev, non-persistent)", value: "memory" },
      ],
    },
    {
      type: "input",
      name: "collection",
      message: "Firestore collection name:",
      default: "annotations",
      when: (a) => a.storage === "firestore",
    },
    {
      type: "input",
      name: "bucket",
      message: "Cloud Storage bucket name:",
      when: (a) => a.storage === "gcs",
    },
    {
      type: "input",
      name: "object",
      message: "Cloud Storage object name:",
      default: "annotations.geojson",
      when: (a) => a.storage === "gcs",
    },
  ]);

  const lines = [
    "# Generated by `npm run config`",
    "",
    "# --- Frontend (Vite) ---",
    `VITE_GOOGLE_MAPS_API_KEY=${answers.mapsKey}`,
    `VITE_API_BASE_URL=${answers.apiBaseUrl}`,
    `VITE_TITLE=${answers.title}`,
    `VITE_DESCRIPTION=${answers.description}`,
    `VITE_LOGO=${answers.logo}`,
    `VITE_FAVICON=${answers.favicon}`,
    "",
    "# --- Server ---",
    "PORT=3000",
    `GCP_PROJECT_ID=${answers.projectId}`,
    `STORAGE_BACKEND=${answers.storage}`,
    `FIRESTORE_COLLECTION=${answers.collection ?? "annotations"}`,
    `GCS_BUCKET=${answers.bucket ?? ""}`,
    `GCS_OBJECT=${answers.object ?? "annotations.geojson"}`,
    "",
  ];

  const envPath = resolve(process.cwd(), ".env");
  writeFileSync(envPath, lines.join("\n"));
  console.log(`\n✓ Wrote ${envPath}`);

  console.log("\nNext steps:");
  console.log("  npm run dev        # start the frontend + API");
  if (answers.storage === "firestore") {
    console.log("  npm run emulator   # (optional) local Firestore emulator — set FIRESTORE_EMULATOR_HOST=localhost:8080 in .env");
  }
  if (answers.storage === "gcs") {
    console.log(`  Ensure bucket gs://${answers.bucket} exists and your credentials have Storage access.`);
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
